org: raaedkabir
app: personal-website
service: stripe-lambda

frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs24.x
  apiGateway:
    shouldStartNameWithService: true
  region: ca-central-1
  stage: dev
  environment:
    STRIPE_SECRET_KEY: ${file(./config.js):STRIPE_SECRET_KEY}

plugins:
  - serverless-offline

functions:
  stripe:
    handler: handler.stripe
    events:
      - http:
          method: POST
          path: stripe
          cors: true
