service: contact-lambda

frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs24.x
  apiGateway:
    shouldStartNameWithService: true
  region: ap-southeast-1
  stage: dev
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 'ses:SendEmail'
          Resource: ['*']

functions:
  contact:
    handler: handler.contact
    events:
      - http:
          method: POST
          path: contact
          cors: true
